// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: api/verificationcode/data/v1/data.proto

/*
Package verificationcodedata is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package verificationcodedata

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
)

var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray

func request_VerificationCodeData_GetLastCode_0(ctx context.Context, marshaler runtime.Marshaler, client VerificationCodeDataClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetLastCodeRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["juvo_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "juvo_id")
	}

	protoReq.JuvoId, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "juvo_id", err)
	}

	msg, err := client.GetLastCode(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

var (
	filter_VerificationCodeData_InsertCode_0 = &utilities.DoubleArray{Encoding: map[string]int{"juvo_id": 0}, Base: []int{1, 1, 0}, Check: []int{0, 1, 2}}
)

func request_VerificationCodeData_InsertCode_0(ctx context.Context, marshaler runtime.Marshaler, client VerificationCodeDataClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq InsertCodeRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["juvo_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "juvo_id")
	}

	protoReq.JuvoId, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "juvo_id", err)
	}

	if err := runtime.PopulateQueryParameters(&protoReq, req.URL.Query(), filter_VerificationCodeData_InsertCode_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.InsertCode(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

// RegisterVerificationCodeDataHandlerFromEndpoint is same as RegisterVerificationCodeDataHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterVerificationCodeDataHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterVerificationCodeDataHandler(ctx, mux, conn)
}

// RegisterVerificationCodeDataHandler registers the http handlers for service VerificationCodeData to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterVerificationCodeDataHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterVerificationCodeDataHandlerClient(ctx, mux, NewVerificationCodeDataClient(conn))
}

// RegisterVerificationCodeDataHandlerClient registers the http handlers for service VerificationCodeData
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "VerificationCodeDataClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "VerificationCodeDataClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "VerificationCodeDataClient" to call the correct interceptors.
func RegisterVerificationCodeDataHandlerClient(ctx context.Context, mux *runtime.ServeMux, client VerificationCodeDataClient) error {

	mux.Handle("GET", pattern_VerificationCodeData_GetLastCode_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_VerificationCodeData_GetLastCode_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_VerificationCodeData_GetLastCode_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_VerificationCodeData_InsertCode_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_VerificationCodeData_InsertCode_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_VerificationCodeData_InsertCode_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_VerificationCodeData_GetLastCode_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 1, 0, 4, 1, 5, 1}, []string{"v1", "juvo_id"}, "getLastCode"))

	pattern_VerificationCodeData_InsertCode_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 1, 0, 4, 1, 5, 1}, []string{"v1", "juvo_id"}, "insert"))
)

var (
	forward_VerificationCodeData_GetLastCode_0 = runtime.ForwardResponseMessage

	forward_VerificationCodeData_InsertCode_0 = runtime.ForwardResponseMessage
)
