// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/verificationcode/data/v1/data.proto

package verificationcodedata

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message for VerificationCodeData.GetLastCode
type GetLastCodeRequest struct {
	// The ID of the user for which to fetch a verification code
	JuvoId               string   `protobuf:"bytes,1,opt,name=juvo_id,json=juvoId,proto3" json:"juvo_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLastCodeRequest) Reset()         { *m = GetLastCodeRequest{} }
func (m *GetLastCodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetLastCodeRequest) ProtoMessage()    {}
func (*GetLastCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_539f1d3fe9282415, []int{0}
}

func (m *GetLastCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastCodeRequest.Unmarshal(m, b)
}
func (m *GetLastCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastCodeRequest.Marshal(b, m, deterministic)
}
func (m *GetLastCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastCodeRequest.Merge(m, src)
}
func (m *GetLastCodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetLastCodeRequest.Size(m)
}
func (m *GetLastCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastCodeRequest proto.InternalMessageInfo

func (m *GetLastCodeRequest) GetJuvoId() string {
	if m != nil {
		return m.JuvoId
	}
	return ""
}

// Request message for VerificationCodeData.GetNewCode
type GetNewCodeRequest struct {
	// The ID of the user for which to fetch a new verification code
	JuvoId               string   `protobuf:"bytes,1,opt,name=juvo_id,json=juvoId,proto3" json:"juvo_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNewCodeRequest) Reset()         { *m = GetNewCodeRequest{} }
func (m *GetNewCodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetNewCodeRequest) ProtoMessage()    {}
func (*GetNewCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_539f1d3fe9282415, []int{1}
}

func (m *GetNewCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNewCodeRequest.Unmarshal(m, b)
}
func (m *GetNewCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNewCodeRequest.Marshal(b, m, deterministic)
}
func (m *GetNewCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNewCodeRequest.Merge(m, src)
}
func (m *GetNewCodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetNewCodeRequest.Size(m)
}
func (m *GetNewCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNewCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNewCodeRequest proto.InternalMessageInfo

func (m *GetNewCodeRequest) GetJuvoId() string {
	if m != nil {
		return m.JuvoId
	}
	return ""
}

// Request message for VerificationCodeData.GetLastCode
type InsertCodeRequest struct {
	// The ID of the user for which to fetch a verification code
	JuvoId               string   `protobuf:"bytes,1,opt,name=juvo_id,json=juvoId,proto3" json:"juvo_id,omitempty"`
	VerificationCode     string   `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertCodeRequest) Reset()         { *m = InsertCodeRequest{} }
func (m *InsertCodeRequest) String() string { return proto.CompactTextString(m) }
func (*InsertCodeRequest) ProtoMessage()    {}
func (*InsertCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_539f1d3fe9282415, []int{2}
}

func (m *InsertCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertCodeRequest.Unmarshal(m, b)
}
func (m *InsertCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertCodeRequest.Marshal(b, m, deterministic)
}
func (m *InsertCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertCodeRequest.Merge(m, src)
}
func (m *InsertCodeRequest) XXX_Size() int {
	return xxx_messageInfo_InsertCodeRequest.Size(m)
}
func (m *InsertCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertCodeRequest proto.InternalMessageInfo

func (m *InsertCodeRequest) GetJuvoId() string {
	if m != nil {
		return m.JuvoId
	}
	return ""
}

func (m *InsertCodeRequest) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

// Request message for VerificationCodeData.GetLastCode
type InsertCodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertCodeResponse) Reset()         { *m = InsertCodeResponse{} }
func (m *InsertCodeResponse) String() string { return proto.CompactTextString(m) }
func (*InsertCodeResponse) ProtoMessage()    {}
func (*InsertCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_539f1d3fe9282415, []int{3}
}

func (m *InsertCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertCodeResponse.Unmarshal(m, b)
}
func (m *InsertCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertCodeResponse.Marshal(b, m, deterministic)
}
func (m *InsertCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertCodeResponse.Merge(m, src)
}
func (m *InsertCodeResponse) XXX_Size() int {
	return xxx_messageInfo_InsertCodeResponse.Size(m)
}
func (m *InsertCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertCodeResponse proto.InternalMessageInfo

// Response message for VerificationCodeData.GetLastCode
type VerificationCode struct {
	// The ID of the user associated with this verification code
	JuvoId string `protobuf:"bytes,1,opt,name=juvo_id,json=juvoId,proto3" json:"juvo_id,omitempty"`
	// The verification code
	VerificationCode     string   `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerificationCode) Reset()         { *m = VerificationCode{} }
func (m *VerificationCode) String() string { return proto.CompactTextString(m) }
func (*VerificationCode) ProtoMessage()    {}
func (*VerificationCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_539f1d3fe9282415, []int{4}
}

func (m *VerificationCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationCode.Unmarshal(m, b)
}
func (m *VerificationCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationCode.Marshal(b, m, deterministic)
}
func (m *VerificationCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationCode.Merge(m, src)
}
func (m *VerificationCode) XXX_Size() int {
	return xxx_messageInfo_VerificationCode.Size(m)
}
func (m *VerificationCode) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationCode.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationCode proto.InternalMessageInfo

func (m *VerificationCode) GetJuvoId() string {
	if m != nil {
		return m.JuvoId
	}
	return ""
}

func (m *VerificationCode) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

func init() {
	proto.RegisterType((*GetLastCodeRequest)(nil), "juvo.verificationcode.data.v1.GetLastCodeRequest")
	proto.RegisterType((*GetNewCodeRequest)(nil), "juvo.verificationcode.data.v1.GetNewCodeRequest")
	proto.RegisterType((*InsertCodeRequest)(nil), "juvo.verificationcode.data.v1.InsertCodeRequest")
	proto.RegisterType((*InsertCodeResponse)(nil), "juvo.verificationcode.data.v1.InsertCodeResponse")
	proto.RegisterType((*VerificationCode)(nil), "juvo.verificationcode.data.v1.VerificationCode")
}

func init() {
	proto.RegisterFile("api/verificationcode/data/v1/data.proto", fileDescriptor_539f1d3fe9282415)
}

var fileDescriptor_539f1d3fe9282415 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcd, 0x4a, 0xeb, 0x40,
	0x14, 0x26, 0x5d, 0xf4, 0x72, 0xe7, 0x5e, 0xb0, 0x1d, 0x8a, 0xad, 0xd1, 0x8a, 0xc6, 0x85, 0xe2,
	0x4f, 0xc6, 0xe8, 0x4e, 0x71, 0x61, 0x15, 0x4a, 0x41, 0xb4, 0x74, 0x21, 0xea, 0xa6, 0x8c, 0xc9,
	0x38, 0x8c, 0xb4, 0x73, 0x62, 0x32, 0x8d, 0x0b, 0x71, 0xe3, 0x1b, 0x14, 0xc1, 0x87, 0x72, 0xab,
	0x8f, 0xe0, 0x83, 0xc8, 0x4c, 0x0b, 0x86, 0x54, 0xda, 0x0a, 0xae, 0x42, 0xf2, 0xfd, 0xcd, 0xf9,
	0xe6, 0x04, 0xad, 0xd2, 0x50, 0x90, 0x84, 0x45, 0xe2, 0x46, 0xf8, 0x54, 0x09, 0x90, 0x3e, 0x04,
	0x8c, 0x04, 0x54, 0x51, 0x92, 0x78, 0xe6, 0xe9, 0x86, 0x11, 0x28, 0xc0, 0xd5, 0xdb, 0x5e, 0x02,
	0x6e, 0x96, 0xe9, 0x1a, 0x46, 0xe2, 0xd9, 0x0b, 0x1c, 0x80, 0x77, 0x18, 0xd1, 0x76, 0x54, 0x4a,
	0x50, 0x86, 0x12, 0x0f, 0xc4, 0x76, 0x39, 0x85, 0xfa, 0x1d, 0xc1, 0xa4, 0x1a, 0x00, 0xce, 0x16,
	0xc2, 0x75, 0xa6, 0x4e, 0x68, 0xac, 0x8e, 0x20, 0x60, 0x2d, 0x76, 0xd7, 0x63, 0xb1, 0xc2, 0x65,
	0xf4, 0x47, 0xa7, 0xb5, 0x45, 0x50, 0xb1, 0x96, 0xac, 0xb5, 0xbf, 0xad, 0xbc, 0x7e, 0x6d, 0x04,
	0xce, 0x26, 0x2a, 0xd6, 0x99, 0x3a, 0x65, 0xf7, 0x53, 0xb1, 0x2f, 0x51, 0xb1, 0x21, 0x63, 0x16,
	0x4d, 0xe5, 0x8d, 0x37, 0x50, 0x31, 0x3d, 0x5d, 0x5b, 0x8f, 0x57, 0xc9, 0x19, 0x4a, 0x21, 0x0d,
	0x68, 0x33, 0xa7, 0x84, 0x70, 0xda, 0x3a, 0x0e, 0x41, 0xc6, 0xcc, 0xb9, 0x40, 0x85, 0xf3, 0x0c,
	0xf3, 0x77, 0xf2, 0x76, 0xde, 0x73, 0xa8, 0x94, 0xb5, 0x3e, 0xa6, 0x8a, 0xe2, 0x17, 0x0b, 0xfd,
	0x4b, 0x35, 0x88, 0x3d, 0x77, 0xec, 0x3d, 0xb9, 0xa3, 0x6d, 0xdb, 0x64, 0x82, 0x24, 0x9b, 0xeb,
	0xac, 0x3c, 0xbd, 0x7d, 0x3c, 0xe7, 0xaa, 0x78, 0x5e, 0xaf, 0xc8, 0xc3, 0x70, 0xba, 0x83, 0xf5,
	0xc7, 0x3d, 0x9e, 0x3a, 0x48, 0xdf, 0x42, 0xe8, 0xab, 0x22, 0xbc, 0x3d, 0x21, 0x64, 0xe4, 0xa2,
	0x6c, 0xef, 0x07, 0x8a, 0x61, 0xff, 0x8b, 0xe6, 0x60, 0x15, 0x67, 0x36, 0x7b, 0x30, 0x61, 0xb8,
	0xf6, 0xcc, 0xeb, 0xe1, 0x7f, 0x1a, 0x8a, 0x81, 0xb1, 0x0f, 0xdd, 0x5a, 0xdf, 0x42, 0xcb, 0x3e,
	0x74, 0xc7, 0x27, 0xd5, 0xe6, 0xbe, 0x6b, 0xbe, 0xa9, 0xf7, 0xb7, 0x69, 0x5d, 0x9d, 0x19, 0x2d,
	0x87, 0x0e, 0x95, 0xdc, 0x85, 0x88, 0x13, 0xce, 0xa4, 0xd9, 0x6d, 0xa2, 0x01, 0x32, 0xee, 0xf7,
	0xda, 0xcf, 0x02, 0xfa, 0xfb, 0x75, 0xde, 0xa8, 0x77, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x00,
	0xce, 0xe0, 0xe7, 0x9a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VerificationCodeDataClient is the client API for VerificationCodeData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VerificationCodeDataClient interface {
	// Returns the last verification code generated for this user
	GetLastCode(ctx context.Context, in *GetLastCodeRequest, opts ...grpc.CallOption) (*VerificationCode, error)
	// Returns the last verification code generated for this user
	InsertCode(ctx context.Context, in *InsertCodeRequest, opts ...grpc.CallOption) (*InsertCodeResponse, error)
}

type verificationCodeDataClient struct {
	cc *grpc.ClientConn
}

func NewVerificationCodeDataClient(cc *grpc.ClientConn) VerificationCodeDataClient {
	return &verificationCodeDataClient{cc}
}

func (c *verificationCodeDataClient) GetLastCode(ctx context.Context, in *GetLastCodeRequest, opts ...grpc.CallOption) (*VerificationCode, error) {
	out := new(VerificationCode)
	err := c.cc.Invoke(ctx, "/juvo.verificationcode.data.v1.VerificationCodeData/GetLastCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verificationCodeDataClient) InsertCode(ctx context.Context, in *InsertCodeRequest, opts ...grpc.CallOption) (*InsertCodeResponse, error) {
	out := new(InsertCodeResponse)
	err := c.cc.Invoke(ctx, "/juvo.verificationcode.data.v1.VerificationCodeData/InsertCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerificationCodeDataServer is the server API for VerificationCodeData service.
type VerificationCodeDataServer interface {
	// Returns the last verification code generated for this user
	GetLastCode(context.Context, *GetLastCodeRequest) (*VerificationCode, error)
	// Returns the last verification code generated for this user
	InsertCode(context.Context, *InsertCodeRequest) (*InsertCodeResponse, error)
}

// UnimplementedVerificationCodeDataServer can be embedded to have forward compatible implementations.
type UnimplementedVerificationCodeDataServer struct {
}

func (*UnimplementedVerificationCodeDataServer) GetLastCode(ctx context.Context, req *GetLastCodeRequest) (*VerificationCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastCode not implemented")
}
func (*UnimplementedVerificationCodeDataServer) InsertCode(ctx context.Context, req *InsertCodeRequest) (*InsertCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertCode not implemented")
}

func RegisterVerificationCodeDataServer(s *grpc.Server, srv VerificationCodeDataServer) {
	s.RegisterService(&_VerificationCodeData_serviceDesc, srv)
}

func _VerificationCodeData_GetLastCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationCodeDataServer).GetLastCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/juvo.verificationcode.data.v1.VerificationCodeData/GetLastCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationCodeDataServer).GetLastCode(ctx, req.(*GetLastCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerificationCodeData_InsertCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationCodeDataServer).InsertCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/juvo.verificationcode.data.v1.VerificationCodeData/InsertCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationCodeDataServer).InsertCode(ctx, req.(*InsertCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VerificationCodeData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "juvo.verificationcode.data.v1.VerificationCodeData",
	HandlerType: (*VerificationCodeDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastCode",
			Handler:    _VerificationCodeData_GetLastCode_Handler,
		},
		{
			MethodName: "InsertCode",
			Handler:    _VerificationCodeData_InsertCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/verificationcode/data/v1/data.proto",
}
